FROM python:3.9

LABEL maintainer="ycui982@aucklanduni.ac.nz"

RUN apt-get update \
    && apt autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY .bashrc /root/.bashrc

ENV PYTHONPATH="${PYTHONPATH}:/ml_app"
WORKDIR "/ml_app"

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip setuptools wheel \
    && pip install --no-cache-dir --progress-bar off -r requirements.txt \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 80
