# Your workflow name.
name: Neurofanos ML pipelines CI

# Run workflow on every push to main branch.
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# Your workflows jobs.
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  file: ./docker/Dockerfile
                  push: true
                  tags: tonycui02/neurofanos-ml-deployment:v1

            - name: Build and Export
              uses: docker/build-push-action@v4
              with:
                  file: ./docker/Dockerfile
                  tags: tonycui02/neurofanos-ml-deployment:v1
                  outputs: type=docker,dest=/tmp/myimage.tar
            
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with: 
                  name: neurofanos-ml-deployment
                  path: /tmp/myimage.tar
